### ISSUE TITLE
Can run maven clean install

### ISSUE THREAD

**Issue by haihoang99** [angerhard/java-etsy-v3-api#1]
I get error when im try to run maven clean and install : An internal error occurred during: "Launching Executing install in myfolder_java-etsy-v3-api".
java.lang.NullPointerException

**Comment by angerhard** [comment]
Puh, I am using maven in IntelliJ to build and also in the pipeline. Can you have a check at "/.github/workflows/maven.yml", if your maven options are different? Do other projects works for you? Using Java 17, latest version of maven?
Otherwise, can you provide a complete stacktrace?

**Comment by angerhard** [comment]
Please reopen the issue if the problem occurs again.
